name: Publish Sub-Split

on:
  push:
    branches:
      - main
  create:
    tags:
      - '*'
  delete:
    tags:
      - '*'

jobs:
  publish:
    runs-on:
      group: thulium-ubuntu-runners
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Generate RetrofitBot token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        id: app-token
        with:
          app-id: ${{ secrets.RETROFIT_BOT_APP_ID }}
          private-key: ${{ secrets.RETROFIT_BOT_PRIVATE_KEY }}
          owner: thulium
          repositories: |
            retrofit-php
            retrofit-php-core
            retrofit-php-client-guzzle7
            retrofit-php-converter-symfony-serializer

      - name: Set RetrofitBot token
        uses: frankdejonge/use-github-token@1.1.0
        with:
          authentication: 'RetrofitBot:${{ steps.app-token.outputs.token }}'
          name: github-actions[bot]
          email: github-actions[bot]@users.noreply.github.com

      - name: Cache splitsh-lite
        id: splitsh-cache
        uses: actions/cache@v4.2.2
        with:
          path: ./.splitsh
          key: ${{ runner.os }}-splitsh-d-101

      - name: Publish using splitish
        uses: frankdejonge/use-subsplit-publish@1.0.0-beta.7
        with:
          source-branch: main
          config-path: ./config.subsplit-publish.json
          splitsh-path: ./.splitsh/splitsh-lite
          splitsh-version: v1.0.1
